In [96]:
import torch

## [1] TENSOR INITIALIZATION

#### BASIC METHOD

In [97]:

#2 rows, 3 columns
my_tensor = torch.tensor([[1,2,3], [4,5,6]])
print(my_tensor)

# set type
my_tensor = torch.tensor([[1,2,3], [4,5,6]], 
                         dtype=torch.float32)
print(my_tensor)

# set device: CUDA
my_tensor = torch.tensor([[1,2,3], [4,5,6]], 
                         dtype=torch.float32,
                         device='cuda')
print(my_tensor)

# set device cpu
my_tensor = torch.tensor([[1,2,3], [4,5,6]], 
                         dtype=torch.float32,
                         device='cpu')
print(my_tensor)

# setup AUTOGRAD 
my_tensor = torch.tensor([[1,2,3], [4,5,6]], 
                         dtype=torch.float32,
                         device='cpu',
                         requires_grad=True)
print(my_tensor)

tensor([[1, 2, 3],
        [4, 5, 6]])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[1., 2., 3.],
        [4., 5., 6.]], requires_grad=True)


In [98]:
DEVICE = 'cuda' if torch.cuda.is_available() else 'cpu'

my_tensor = torch.tensor([[1,2,3], [4,5,6]], 
                         dtype=torch.float32,
                         device=DEVICE,
                         requires_grad=True)
print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.requires_grad)
print(my_tensor.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
True
torch.Size([2, 3])


#### COMMON INITIALIZATION METHODS

In [99]:
x = torch.empty(size=(2,4))
print(x)

x = torch.zeros(size=(3,2))
print(x)

x = torch.rand(size=(2,2))
print(x)

x = torch.ones(size=(2,2))
print(x)

x = torch.eye(3,5)
print(x)

x = torch.arange(start=0, end=5, step=1)
print(x)

x = torch.linspace(start=0.1, end=1, steps=3)
print(x)

x = torch.empty(size=(2,4)).normal_(mean=0, std=1)
print(x)

x = torch.empty(size=(2,4)).uniform_(0, 1)
print(x)

x = torch.diag(torch.ones(3))
print(x)

x = torch.diag(torch.rand(3))
print(x)

tensor([[-4.2880e+37,  1.5849e-42,  2.3694e-38,  2.3694e-38],
        [ 2.3694e-38,  2.3694e-38,  1.4013e-45,  0.0000e+00]])
tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])
tensor([[0.2744, 0.2369],
        [0.8411, 0.5270]])
tensor([[1., 1.],
        [1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.5500, 1.0000])
tensor([[-0.8405,  0.1627,  0.7913,  0.6105],
        [ 0.1480, -1.1028, -2.4312,  0.9010]])
tensor([[0.9844, 0.1806, 0.1119, 0.7647],
        [0.1661, 0.5646, 0.7710, 0.0682]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
tensor([[0.6284, 0.0000, 0.0000],
        [0.0000, 0.3021, 0.0000],
        [0.0000, 0.0000, 0.2384]])


#### INITIALIZE AND CONVERT TENSORS TO OTHER TYPES

In [100]:

tensor = torch.arange(4)
print(tensor)
# to bool
print(tensor.bool())

# to int16
print(tensor.short())

# to int64
print(tensor.long())

# to GTX20+ SERIES float16
print(tensor.half())

# to=float32
print(tensor.float())

# to=float64
print(tensor.double())

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


In [101]:
import numpy as np
np_array = np.zeros([5,5])
print(np_array)
t = torch.from_numpy(np_array)
print(t)
np_arr_back = t.numpy()
print(np_arr_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


---

## [2] TENSOR MATH COMPARISON

In [102]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# Addition
z1 = torch.empty(3)
torch.add(x,y, out=z1)
print(z1)

z2 = torch.add(x,y)
print(z2)

# Subtraction
z = x - y
print(z)

# Division
z = torch.true_divide(x, y)

# inplace operations
t = torch.zeros(3)
t.add_(x)
print(t)
t +=x
print(t)

# Exponentiation
z = x.pow(2)
print(z)
z = x ** 2
print(z)

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([1., 2., 3.])
tensor([2., 4., 6.])
tensor([1, 4, 9])
tensor([1, 4, 9])


In [103]:
# Simple comparison
z = x > 0
print(z)
z = x < 0
print(z)

tensor([True, True, True])
tensor([False, False, False])


In [104]:
# Matrix Multiplicatoin
x1 = torch.rand((2, 5))
print(x1)
x2 = torch.rand((5, 3))
print(x2)
print()
x3 = torch.mm(x1, x2)
print(x3)
x3 = x1.mm(x2)
print(x3)

tensor([[0.0111, 0.5535, 0.7304, 0.3213, 0.6833],
        [0.4622, 0.2361, 0.2134, 0.5512, 0.4845]])
tensor([[0.0472, 0.2002, 0.1757],
        [0.1985, 0.6147, 0.5498],
        [0.1631, 0.2351, 0.9611],
        [0.5102, 0.7476, 0.2842],
        [0.2781, 0.3732, 0.5061]])

tensor([[0.5835, 1.0093, 1.4454],
        [0.5195, 0.8807, 0.8180]])
tensor([[0.5835, 1.0093, 1.4454],
        [0.5195, 0.8807, 0.8180]])


In [105]:
# Matrix Exponentiation
z = x * y
print(z)

tensor([ 9, 16, 21])


In [106]:
# Dot Product
z = torch.dot(x, y)
print(z)

tensor(46)


In [107]:
# Batch Matrix Multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m, p))
out_bmm = torch.bmm(tensor1, tensor2) # (batch, n ,p)

In [108]:
# Example of Broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2
print(z)

z = x1 ** x2
print(z)

tensor([[ 0.4231, -0.2160, -0.3311,  0.7090,  0.2294],
        [ 0.4849, -0.1671,  0.5297,  0.0828,  0.3464],
        [-0.0661, -0.2243,  0.0735,  0.2221,  0.2755],
        [ 0.2120, -0.6435, -0.0284,  0.4647,  0.2688],
        [ 0.1056, -0.0543, -0.2665,  0.0379,  0.6752]])
tensor([[0.9562, 0.6047, 0.3465, 0.9925, 0.8378],
        [0.9874, 0.6467, 0.9725, 0.9473, 0.8819],
        [0.6566, 0.5974, 0.7418, 0.9666, 0.8562],
        [0.8407, 0.1422, 0.6732, 0.9828, 0.8536],
        [0.7756, 0.7395, 0.4483, 0.9349, 0.9764]])


In [111]:
# Other tensor operations
print(x)
print(y)

sum_x = torch.sum(x, dim=0)
print(sum_x)

values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)
print(abs_x)

z = torch.argmax(x, dim=0)
print(z)

mean_x = torch.mean(x.float(), dim=0)
print(mean_x)

z = torch.eq(x, y)
print(z)

sorted_y, indices = torch.sort(y, dim=0, descending=False)
print(sorted_y)

z = torch.clamp(x, min=0)
print(z)


xe = torch.tensor([1,0,1,1,1], dtype=torch.bool)
print(xe)
z = torch.any(xe)
print(z)
z = torch.all(xe)
print(z)

tensor([1, 2, 3])
tensor([9, 8, 7])
tensor(6)
tensor([1, 2, 3])
tensor(2)
tensor(2.)
tensor([False, False, False])
tensor([7, 8, 9])
tensor([1, 2, 3])
tensor([ True, False,  True,  True,  True])
tensor(True)
tensor(False)


---

## [3] TENSOR INDEXING

In [116]:
batch_size = 10
features = 25
x = torch.rand([batch_size, features])

# x[0, :1]
print(x[0])

# first features of all exaples
print(x[:, 0])

# get third exaple, first 10 features 0:10 -> [0,1,..8,9]
print(x[2, 0:10])

#assignemnt
x[0,0] = 100

tensor([0.5869, 0.4874, 0.0774, 0.0972, 0.5640, 0.3625, 0.9628, 0.0314, 0.1447,
        0.8513, 0.8807, 0.0196, 0.2675, 0.8155, 0.9427, 0.4994, 0.9091, 0.6812,
        0.3687, 0.5001, 0.1317, 0.5315, 0.8177, 0.9099, 0.3565])
tensor([0.5869, 0.9958, 0.7690, 0.0202, 0.9443, 0.0072, 0.7464, 0.4991, 0.4456,
        0.4877])
tensor([0.7690, 0.0726, 0.3442, 0.3542, 0.9857, 0.7030, 0.5595, 0.5516, 0.2979,
        0.5484])


In [120]:
# Fancy indexing
x = torch.arange(10)
print(x)

indices = [2,5,8]
print(x[indices])


x = torch.rand((3,5))
print(x)
rows = torch.tensor([1,0])
cols = torch.tensor([4,0])
print(x[rows, cols].shape)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([2, 5, 8])
tensor([[0.2281, 0.0016, 0.6040, 0.4410, 0.2619],
        [0.6839, 0.3381, 0.9519, 0.2881, 0.9389],
        [0.3934, 0.8062, 0.1746, 0.2786, 0.6788]])
torch.Size([2])


In [126]:
# Advanced indexing
x = torch.arange(10)
print(x)
print(x[(x<2) | (x>8)])
print(x[(x<2) & (x>8)])
print(x[x.remainder(2) == 0])

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([0, 1, 9])
tensor([], dtype=torch.int64)
tensor([0, 2, 4, 6, 8])


In [130]:
# Useful operations
print(torch.where(x>5, x, x*2))

print(torch.tensor([0,3,24,1,3,4,4,2,3]).unique())

print(x.ndimension()) # single vector = simgle dimension

print(x.numel())

tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([ 0,  1,  2,  3,  4, 24])
1
10


---

## [4] TENSOR RESHAPING

In [132]:
x = torch.arange(9)
print(x)

# contiguous tensor in memory
x_3x3 = x.view(3, 3)
print(x_3x3)

# safer, but performance loss compared to view
x_3x3 = x.reshape(3, 3)
print(x_3x3)


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [135]:
# Advanced
y = x_3x3.t() # transposed
print(y)

#print(y.view(9))

print(y.contiguous().view(9))

tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [137]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

# concatenate
print(torch.cat((x1, x2), dim=0).shape)
print(torch.cat((x1, x2), dim=1).shape)

# flattening
z = x1.view(-1)
print(z)

torch.Size([4, 5])
torch.Size([2, 10])
tensor([0.2494, 0.0966, 0.9621, 0.0216, 0.4436, 0.0032, 0.3570, 0.3868, 0.3764,
        0.3326])


In [140]:
# Adding complexity
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

z = x.permute(0, 2, 1)
print(z.shape)

torch.Size([64, 10])
torch.Size([64, 5, 2])


In [141]:
x = torch.arange(10)
print(x.unsqueeze(0).shape)
print(x.unsqueeze(1).shape)

torch.Size([1, 10])
torch.Size([10, 1])


In [146]:
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
print(x.shape)
print(x)


torch.Size([1, 1, 10])
tensor([[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]]])


In [147]:
z = x.squeeze(1)
print(z.shape)
print(z)

torch.Size([1, 10])
tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
